name: "Echo some text"
description: "Really important Action so we can echo some text"
inputs:
  text: 
    description: 'text to echo'
    required: true

runs:
  using: "composite"
  steps:
    - name: Echo
      id: echo      
      shell: bash
      run: |        
        echo ${{ inputs.text }}